test_access_secret_acc_id (test_msys_access_keys.TestMsysAccessKeys) ... Test Method : test_access_secret_acc_id checks for whether unique generated between Access id, Account id and secret id, Account id
ok
test_creationTimestamp (test_msys_access_keys.TestMsysAccessKeys) ... Test Method : test_creationTimestamp Checks for generated Timestamp is not null
ok
test_lastUsedTimestamp (test_msys_access_keys.TestMsysAccessKeys) ... Test Method : test_lastUsedTimeStamp Checks for generated last used Timestamp is not null
ok
test_status (test_msys_access_keys.TestMsysAccessKeys) ... Test Method : test_status checks whether status of access Key is ACTIVE or not..
ok
test_userID (test_msys_access_keys.TestMsysAccessKeys) ... Test Method: test_userID checks whether userID created is NUll or Not
ok
test_account_id (test_msys_accounts.TestMsysAccounts) ... test_account_id method tests that account Id generated is not Null
ok
test_account_name (test_msys_accounts.TestMsysAccounts) ... Checking Account Names Existence in Table
Account Names in Database Table Must match with Account Names in JSON Input Data File
Assertion error: Items in the first set but not the second:
'TestAccount100'
FAIL
test_number_of_records (test_msys_accounts.TestMsysAccounts) ... test_number_of_records to check for number of records present in Msys Accounts table with Input Data Records.
To pass test_number_of_records Test Method Both Number of Records should be same..
Assertion error: 6 != 4 : Number of records are not equal
FAIL
test_password (test_msys_accounts.TestMsysAccounts) ... Checking Password matching of Password record in Database Table and Input Data File
Assertion error: Lists differ: ['TestAccount5', 'TestAccount3'] != []

First list contains 2 additional elements.
First extra element 0:
'TestAccount5'

- ['TestAccount5', 'TestAccount3']
+ [] : Passwords mismatch for accounts: ['TestAccount5', 'TestAccount3']
FAIL
test_arn (test_msys_buckets.TestMsysBuckets) ... Test Method : test_arn to check for generated arn is not null
ok
test_bucketAccID_accessID_secretkey (test_msys_buckets.TestMsysBuckets) ... Test Method : test_bucketAccID_accessID_secretkey , to map bucket Account Id with Access Key Id and secret Id
ok
test_bucketID (test_msys_buckets.TestMsysBuckets) ... Test Method : test_bucketID to check for generated Bucket Id is not null
ok
test_bucketName (test_msys_buckets.TestMsysBuckets) ... Test Method: test_bucketName to compare for bucket Names present in db Table with Input User Data
AssertionError : Items in the first set but not the second:
'TestBucket3'
'TestBucket2'
Items in the second set but not the first:
'TestBucket300'
'TestBucket100'
FAIL
test_creationTimestamp (test_msys_buckets.TestMsysBuckets) ... Test Method : test_creationTimestamp to check for creation Time stamp is not null
ok
test_bucketID (test_msys_objects.TestMSysObjects) ... Logging for test_bucketID
Checking for Comparision of BucketID from Msys_Buckets Table and BucketID from Msys_Objects Table
Bucketid 'bucket677562552' from Objects Table found in Buckets table.
Bucketid 'bucket213518639' from Objects Table found in Buckets table.
Bucketid 'bucket318628394' from Objects Table found in Buckets table.
Bucketid 'bucket318628394' from Objects Table found in Buckets table.
Bucketid 'bucket213518639' from Objects Table found in Buckets table.
ok
test_bucket_name_from_input_file (test_msys_objects.TestMSysObjects) ... Logging for test_bucket_name_from_input_file
To check for the existence of Bucket Names from Input JSON Data File
Bucket name 'TestBucket3' found in table.
Bucket name 'TestBucket1' found in table.
Bucket name 'TestBucket1' found in table.
Bucket name 'TestBucket4' found in table.
Bucket name 'TestBucket4' found in table.
Bucket name 'TestBucket8' not found in table.
Bucket name 'TestBucket10' not found in table.
test_creationTimeStamp (test_msys_objects.TestMSysObjects) ... Logging for test_creationTimeStamp
Checking TimeStamp generated value is not NUll
ok
test_objectID (test_msys_objects.TestMSysObjects) ... Logging for test_objectID
Checking ObjectID generated value is not NUll
ok
test_object_file (test_msys_objects.TestMSysObjects) ... Logging for test_object_file
Checking for Object File Names from Input Json Data file.
['test1.txt', 'test2.txt', 'test4.txt', 'test5.txt', 'test3.txt']
Assertion error: Items in the second set but not the first:
'test6.txt'
'test8.txt'
FAIL
test_accountId (test_msys_users.TestMsysUsers) ... Test method test_accountID checks for accountID generated is not Null
Test method test_accountID to get passed , test_accountID generated is not NUll
ok
test_arn (test_msys_users.TestMsysUsers) ... Test method test_arn checks for arn generated is not Null
Test method test_arn to get passed , test_arn generated is not NUll
ok
test_path (test_msys_users.TestMsysUsers) ... Test method test_path checks for path generated is not Null
Test method test_path to get passed , path generated is not NUll
ok
test_timestamp (test_msys_users.TestMsysUsers) ... Test method test_timestamp checks for timestamp generated is not Null
Test method test_arn to get passed , timestamp generated is not NUll
ok
test_userID (test_msys_users.TestMsysUsers) ... Test method test userID checks for Userid is not Null
Test method test_userID to get passed , userId generated is not NUll
ok
test_userName (test_msys_users.TestMsysUsers) ... Test Method test_userName checks for the existence of user Names in db table and compare with input user data file
ok

======================================================================
FAIL: test_account_name (test_msys_accounts.TestMsysAccounts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abhishek/git_workspace/python-db-connectivity/test_msys_accounts.py", line 63, in test_account_name
    raise e
  File "/home/abhishek/git_workspace/python-db-connectivity/test_msys_accounts.py", line 60, in test_account_name
    self.assertSetEqual(db_account_names_set, json_account_names_set)
AssertionError: Items in the first set but not the second:
'TestAccount100'

======================================================================
FAIL: test_number_of_records (test_msys_accounts.TestMsysAccounts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abhishek/git_workspace/python-db-connectivity/test_msys_accounts.py", line 96, in test_number_of_records
    raise e
  File "/home/abhishek/git_workspace/python-db-connectivity/test_msys_accounts.py", line 93, in test_number_of_records
    self.assertEqual(len(self.rows), len(self.input_data), "Number of records are not equal")
AssertionError: 6 != 4 : Number of records are not equal

======================================================================
FAIL: test_password (test_msys_accounts.TestMsysAccounts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abhishek/git_workspace/python-db-connectivity/test_msys_accounts.py", line 86, in test_password
    raise e
  File "/home/abhishek/git_workspace/python-db-connectivity/test_msys_accounts.py", line 83, in test_password
    self.assertListEqual(mismatched_accounts, [], f"Passwords mismatch for accounts: {mismatched_accounts}")
AssertionError: Lists differ: ['TestAccount5', 'TestAccount3'] != []

First list contains 2 additional elements.
First extra element 0:
'TestAccount5'

- ['TestAccount5', 'TestAccount3']
+ [] : Passwords mismatch for accounts: ['TestAccount5', 'TestAccount3']

======================================================================
FAIL: test_bucketName (test_msys_buckets.TestMsysBuckets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abhishek/git_workspace/python-db-connectivity/test_msys_buckets.py", line 104, in test_bucketName
    raise err
  File "/home/abhishek/git_workspace/python-db-connectivity/test_msys_buckets.py", line 101, in test_bucketName
    self.assertSetEqual(self.db_bucketNames, self.input_usernames)
AssertionError: Items in the first set but not the second:
'TestBucket3'
'TestBucket2'
Items in the second set but not the first:
'TestBucket300'
'TestBucket100'

======================================================================
FAIL: test_bucket_name_from_input_file (test_msys_objects.TestMSysObjects) (element='TestBucket8')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abhishek/git_workspace/python-db-connectivity/test_msys_objects.py", line 51, in test_bucket_name_from_input_file
    self.assertIn(element, Table_BucketNames)
AssertionError: 'TestBucket8' not found in ['TestBucket2', 'TestBucket1', 'TestBucket4', 'TestBucket3']

======================================================================
FAIL: test_bucket_name_from_input_file (test_msys_objects.TestMSysObjects) (element='TestBucket10')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abhishek/git_workspace/python-db-connectivity/test_msys_objects.py", line 51, in test_bucket_name_from_input_file
    self.assertIn(element, Table_BucketNames)
AssertionError: 'TestBucket10' not found in ['TestBucket2', 'TestBucket1', 'TestBucket4', 'TestBucket3']

======================================================================
FAIL: test_object_file (test_msys_objects.TestMSysObjects)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/abhishek/git_workspace/python-db-connectivity/test_msys_objects.py", line 69, in test_object_file
    raise e
  File "/home/abhishek/git_workspace/python-db-connectivity/test_msys_objects.py", line 66, in test_object_file
    self.assertSetEqual(Table_ObjectNames_set, InputData_ObjectNames)
AssertionError: Items in the second set but not the first:
'test6.txt'
'test8.txt'

----------------------------------------------------------------------
Ran 25 tests in 0.658s

FAILED (failures=7)
